query Courses(  $is_featured: courses_media_bool_exp
) {
  courses {
    level
    id
    price
    description
    title
    course_instructors {
      instructor {
        name
        position
        profile_picture
      }
    }
    duration
    summary

    course_schedules {
      number_of_classes
      class_type

      shift
    }
    courses_media(where:$is_featured){
      url
    }
  }
}
