query MyQuery($filter: instructors_bool_exp) {
  instructors(where: $filter) {
    name
    position
    profile_picture
    id
    bio
    instructor_social_medias {
      social_medium {
        social_media
        icon
        __typename
      }
      link
      order
      __typename
    }
    instructor_experiences {
      entity {
        logo
        name
      }
      position {
        name
      }
      total_years_of_experience
      remark
    }
    instructor_educational_details {
      education_level {
        description
        name
      }
      description
      educational_institution {
        name
        logo
        description
      }
      end_date
      start_date
    }
    course_instructors {
      course {
        title
        venue
        price
        level
        has_certifications
        duration
        description
        summary
        id
        courses_media {
          is_thumbnail
          url
        }
        course_schedules {
          class_type
          number_of_classes
          shift
        }
      }
      course_id
      __typename
    }
    __typename
  }
}
